name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - feature/api-resilience-and-testing
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Navigate to project directory
      run: cd TP23/services/epf-flower-data-science

    - name: Install dependencies
      run: |
        cd TP23/services/epf-flower-data-science
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd TP23/services/epf-flower-data-science
        pytest tests
